Github Abmonition Feature
spmse/dev-blog-template pull request #6
Opened 2024-10-25 07:05 UTC by mihaiandreineacsu

2024-10-25 18:47 UTC, spmse reviewed
Nice one! 

In the best case add some more documentation text into the mdx file, so that people know about the component and how to use it.

After documentation is complete we can merge this branch

2024-10-28 14:48 UTC, henrymanke requested changes
Hi @mihaiandreineacsu,
we add some minor improvements.

2024-10-28 14:48 UTC, henrymanke commented on src/components/GithubLinkAdmonition/index.tsx
> +
```suggestion
type AdmonitionType = "info" | "tip" | "warning" | "note" | "danger";
```

2024-10-28 14:48 UTC, henrymanke commented on src/components/GithubLinkAdmonition/index.tsx
> +  type?: string;
```suggestion
  type?: AdmonitionType;
```

2024-12-19 14:28 UTC, closed without merging